# Numpy

In [4]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

In [ ]:
b = np.array([1,2,3,4,5], dtype='f')
print(b)

# Numpy Dimensions

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a.ndim)

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a[0,0])

In [ ]:
a = np.array([[1,2,3], [4,5,6,7]])
print(a)
# Arrays should have homogenous shape

# 3D Array

In [ ]:
a = np.array([[[1,2,3], [4,5,6,]],[[-1,-2,-3],[-4,-5,-6]]])
print(a)
print(a.ndim)

In [ ]:
print(a[0,1,2])

# Shape

In [ ]:
a = np.array([[[1,2,3], [4,5,6,]],[[-1,-2,-3],[-4,-5,-6]]])
print(a.shape)
#0 no. array
#1 no. array in array
#2 no. of element

# Other Properties

In [ ]:
a.size

In [ ]:
a.nbytes

# Arange

In [ ]:
d = np.arange(100)
print(d)

In [ ]:
e = np.arange(50,100,5)
print(e)

# Random

In [ ]:
f = np.random.permutation(np.arange(10))
print(f)

In [ ]:
import matplotlib.pyplot as plt
f = np.random.rand(1000)
plt.hist(f, bins=10)

In [ ]:
f = np.random.randn(100000)
plt.hist(f, bins=100)

In [ ]:
f = np.random.rand(2,2,4,2)
print(f)

# Reshape

In [ ]:
g = np.arange(50).reshape(5,10)
print(g)

In [ ]:
g = np.arange(50).reshape(2,5,5)
print(g)

# Slicing

In [ ]:
a[1:5]      # index 1 till 5 but not 5
a[:5]       # index 0 till 5 but not 5
a[2:]       # index 2 until last element
a[::-1]     # (reverse the array) end till start
a[::2]      # from start to end every other element
a[::2,:]    #

In [ ]:
A=np.arange(100)
B = A[3:10]
print(B)

In [ ]:
B[1] = 9999
print(B)
print(A)

In [ ]:
A=np.arange(100)
B = A[3:10].copy()
print(B)

In [ ]:
B[1] = 9999
print(B)
print(A)

In [ ]:
A[::5]

In [ ]:
A[::-5]

In [ ]:
print(A)

In [ ]:
idx = np.argwhere(A==10)[0][0]
print(idx)
A[10]

In [ ]:
A = np.round(10*np.random.rand(5,4))
A

In [ ]:
A[3,2]
A[3,:]

# Numpy Linear Algebra

In [3]:
import numpy as np
import numpy.linalg as la

In [4]:
la.inv(np.random.rand(3,3))

array([[ 0.35434919, -1.00674396,  0.97212416],
       [-0.49939956,  0.73685857,  0.5942887 ],
       [ 0.96939916,  0.81763178, -1.38405537]])

In [7]:
A = np.round(10*np.random.rand(5,4))
A

array([[ 8.,  9., 10.,  4.],
       [ 2.,  7.,  4.,  8.],
       [ 2.,  3.,  5.,  4.],
       [ 6.,  7.,  3.,  1.],
       [ 8.,  3.,  5.,  2.]])

In [8]:
A.sort(axis=0)
A

array([[ 2.,  3.,  3.,  1.],
       [ 2.,  3.,  4.,  2.],
       [ 6.,  7.,  5.,  4.],
       [ 8.,  7.,  5.,  4.],
       [ 8.,  9., 10.,  8.]])

In [9]:
A.sort(axis=1)
A

array([[ 1.,  2.,  3.,  3.],
       [ 2.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [ 4.,  5.,  7.,  8.],
       [ 8.,  8.,  9., 10.]])

# More Numpy Indexing

In [10]:
A[A>5]

array([ 6.,  7.,  7.,  8.,  8.,  8.,  9., 10.])

In [19]:
B = A[(A<9) & (A>5)]
B

array([6., 7., 7., 8., 8., 8.])

# Broadcasting

In [35]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A+B+ 5
C

array([[11, 13],
       [15, 17]])

In [41]:
A = np.round(10*np.random.rand(2,2))
B = np.round(10*np.random.rand(2,3))
A

array([[6., 1.],
       [7., 0.]])

In [43]:
B

array([[ 3.,  0., 10.],
       [ 6.,  2.,  6.]])

In [42]:
C = np.hstack((A,B))
C

array([[ 6.,  1.,  3.,  0., 10.],
       [ 7.,  0.,  6.,  2.,  6.]])

# Numpy(Speed: ufuncs)

In [47]:
b = np.random.rand(10000000)
%timeit sum(b)
%timeit np.sum(b)

840 ms ± 22.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11.1 ms ± 157 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [48]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s
%timeit mySum(b)

1.09 s ± 43.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
